### ISSUE TITLE
Proper application icon/logo

### ISSUE THREAD

**Issue by alxlg** [daehruoydeef/Yin-Yang#12]
In case you are looking for a proper icon for the project instead of classic yin-yang symbol I just made this one in Breeze style:

![immagine](https://user-images.githubusercontent.com/26327475/54630468-365c6080-4a7a-11e9-8775-1591c5e346b1.png)

**Comment by daehruoydeef** [comment]
Thank you I will definetly use this on the next release!

**Comment by alxlg** [comment]
@daehruoydeef here there is the SVG source for the icon: https://share.kde.org/s/5KnjzJjJoC5bepd

I already sent you the link to the light+dark wallpapers for KDE Neon and I'm thinking to draw more light+dark wallpapers :)

In fact I discovered the command to switch Look&Feel some time ago and I was trying to write a script like yours, but you made a great work and I hope it will improve over the time!

I already reported some issues and I think that to solve the packaging issue you could look into Flatpak, that would make Yin-yang showcased in a store like FlatHub.org

**Comment by daehruoydeef** [comment]
Thanks, I will set up a service and would like to gather all wallpapers there. I would really like to package this tool as a flatpak, snap and appimage but failed with my first version miserably. I will try again and will make this available for as many Distros as I can. 
I would really like to see this tool becoming the Auto Nightmode standard on Linux but there is still a long way to go. Thank you for your effort really looking forward for your Wallpapers and other contributions.
