### ISSUE TITLE
Checking/unchecking the KDE checkbox grows the list of themes

### ISSUE THREAD

**Issue by eogan** [daehruoydeef/Yin-Yang#15]
The list of themes is populated when checking the combo box and not at application start. 

- If KDE is unchecked the list id too small to display the value
- Checking/unchecking KDE adds more and more items to the list

**Comment by daehruoydeef** [comment]
Could you please provide a Screenshot what the list looks like after you have clicked the checkbox several times? I cannot reproduce this right now.

**Comment by eogan** [comment]
Sorry I don't know yet how to do screenshots here.-serious-
 It looks like .addlist() is called each time you check the box. Anyway that's not blocking. I'll try to make s screen l8r.

**Comment by daehruoydeef** [comment]
Thanks I fixed the Issues and the Code should be up every moment. 

I now check with
`if (self.ui.combo_kde_light.count() <= 0 and sef.ui.combo_kde_dark.count() <= 0)`
and only append themes of the Count of the items inside the dropdown is 0.
