### ISSUE TITLE
Follow sunrise and sunset

### ISSUE THREAD

**Issue by eogan** [daehruoydeef/Yin-Yang#16]
I thought it would be a nice feature that the schedule is following the natural sunrise/sunset. I found code that does return thoose values if you are interested. 

I don't know how to use github to "push" code so you'll have to explain me.

**Comment by daehruoydeef** [comment]
Hey I would like to implement this. You can send me te code as a 
[GitHub Gist](https://gist.github.com/), you can upload code snippets. Would be really great and I will sure implement this!

**Comment by eogan** [comment]
Ok, here it is:
https://gist.github.com/eogan/7df2ff36058a8d4c6469b71fbffc86b8 <https://gist.github.com/eogan/7df2ff36058a8d4c6469b71fbffc86b8>

The gist didn't use the name I gave it but the name of the larger file.

Cheers,
Eogan

-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Mar 30, 2019, 8:32 AM by notifications@github.com:

**Comment by daehruoydeef** [comment]
I looked at the code and it this will not find place in Yin-Yang 3.0 so I removed the milestown this needs more attention I cannot give right now. 
I would really love if this could find place in a later Version of Yin-Yang. Right now I try to get stable KDE, Gnome and Budgie support.

**Comment by tneo** [comment]
Can you link it to the KDE Night color control? Once that is fully at day or night color setting Yin-Yang should switch theme.

**Comment by daehruoydeef** [comment]
Yin yang does support a new flag there is no gui option actually. I will add some documentation in the following days on how to enable this feature
