### ISSUE TITLE
Dynamic Wallpaper Plugin

### ISSUE THREAD

**Issue by daehruoydeef** [daehruoydeef/Yin-Yang#17]
- add a Button to use Dynamic Wallpapers 
- lets you specify a folder where you can place your wallpapers labled as 1-24.png
- if Dynamic is set it will look into this Folder and change the wallpapers dynamically

**Comment by eogan** [comment]
There is no need for that, the user should just use:
https://github.com/zzag/dynamic-wallpaper

See discussion and links here also:
https://www.reddit.com/r/kde/comments/b2prs8/dynamic_wallpaper_plugin/

If the user wants just one light and one dark wallapper he can use Yin-Yang. If he wants a dynamic wallpaper he can use "Dynamic Wallpaper Plugin" via "Configure desktop". 

Dynamic is not just changing the wallpaper every hour or so, it takes into account the position of the sun where you are and the position of the sun when the picture was taken. So the background will reflect the actual position of the sun in your location !! :-)

Look in the links to find more info.

**Comment by eogan** [comment]
Here is a sample dynamic wallpaper:
https://github.com/eogan/earth-dynamic-wallpaper/releases

**Comment by daehruoydeef** [comment]
Agreed, I actually thaught about building a extra tool for Dynamic switching and liked the idea of implementing this into Yin-Yang but if people want this extra funtionality they can use the tool you linked above.
