### ISSUE TITLE
KDE not recognised

### ISSUE THREAD

**Issue by Optica1** [daehruoydeef/Yin-Yang#18]
Just installed latest master.
Before starting yin-yang, there is no file yin_yang.json. It gets created on first GUI startup. 
I believe this is normal behaviour?

When I go to settings, i enable KDE and get the reply 

"""
Traceback (most recent call last):
  File "/opt/yin-yang/src/gui.py", line 147, in toggleKdeFields
    self.getKdeThemes()
  File "/opt/yin-yang/src/gui.py", line 138, in getKdeThemes
    ["notify-send", "It looks like you are not running KDE"])
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Bestand of map bestaat niet: 'notify-send': 'notify-send'

"""

If I then go back, I can't open settings anymore.

This problem is resolved by manually adding 'kde' in yin_yang.json.

I believe it would be easier to create the json on installation and check for DE at that point in time?

**Comment by daehruoydeef** [comment]
Could you please post the output of
echo $GDMSESSION 
I use this command to recognise the Desktop. Could you also append what system you are running this on?

It looks like the problem is that it cannot find the command notify-send which should be standard on most distros. I plan on removing the notification feature completly. 
Regarding the config creation on install, I feel like this would complicate stuff if I try to package this tool as a flatpak or snap since there would be no install script which can be run. I am still searching for a better way.

**Comment by Optica1** [comment]
I'm running Ubuntu 18.10 on plasma version 5.13.5
Kernel 5.0.1-050001-generic

$GDMSESSION contains nothing. 
I think gdm is the gnome display manager and I'm running on sddm? Not sure if thats why the variable is empty.

**Comment by daehruoydeef** [comment]
Thanks good catch I feel like I need to implement a diffrent system for desktop recognision maybe a hybrid between
$GDMSESSION and $XDG_DESKTOP_SESSION
 Could you try to echo $XDG_DESKTOP_SESSION
and post the output would be oft great help

**Comment by daehruoydeef** [comment]
@Optica1 please check if latest commit fixed this for you, I tried a more general way on Desktop Env detection. Simply clone the repository, run sudo sh install.sh, and open the Yin-Yang gui by either running yin-yang -gui or simply searching for the program on your System. Would be nice if you could report back if this works so I can close the issue.

**Comment by Optica1** [comment]
Yes it works! Nice job!
