### ISSUE TITLE
unrecognized arguments: -gui

### ISSUE THREAD

**Issue by yochananmarqos** [daehruoydeef/Yin-Yang#22]
I just built with the latest commit c34ac9d:

```
$ env QT_AUTO_SCREEN_SCALE_FACTOR=1 sh /usr/bin/yin-yang -gui
usage: main.py [-h] [-t] [-s]
main.py: error: unrecognized arguments: -gui
```
```
$ yin-yang 
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "/opt/yin-yang/main.py", line 59, in <module>
    main()
  File "/opt/yin-yang/main.py", line 37, in main
    window = gui.MainWindow()
  File "/opt/yin-yang/src/gui.py", line 184, in __init__
    self.ui.setupUi(self)
  File "/opt/yin-yang/src/ui/mainwindow.py", line 71, in setupUi
    sys._MEIPASS+"/assets/yin-yang.svg"))
AttributeError: module 'sys' has no attribute '_MEIPASS'
```

**Comment by daehruoydeef** [comment]
I will push a patch tomorrow. Basically what you want for now is to replace the currently used .desktop file with the one provided inside the build folder. Please note that this is the Beta and it is currently unstable.

**Comment by yochananmarqos** [comment]
FYI, the icon path in `build.sh` & `yin-yang.desktop` should be `/usr/share/icons/hicolor/scalable/app/yin-yang.svg`. Why are you using the 32x32 PNG?

**Comment by daehruoydeef** [comment]
I fixed the Icons inside the AppImage and also the -gui flag.
In order to fix this please update the yin-yang.desktop file and remove the -gui flag. Yin-Yang will now start with a gui by default
