### ISSUE TITLE
Theme names don't fit 

### ISSUE THREAD

**Issue by badervalsan72** [daehruoydeef/Yin-Yang#23]
When selecting KDE themes on the settings option, some of the larger names don't fit the box. 
![example](https://user-images.githubusercontent.com/44733398/57578014-33aa3600-7441-11e9-8dbf-c65b0aa6e1ad.png)

**Comment by daehruoydeef** [comment]
Since I am not running a KDE Desktop I could use some help for this.

If any one is interested in fixing this for KDE you should fork this Project, this is where the person should look: [GETTING KDE THEMES](https://github.com/daehruoydeef/Yin-Yang/blob/master/src/gui.py#L124)
