### ISSUE TITLE
Error loading Python lib with AppImage

### ISSUE THREAD

**Issue by brenthuisman** [daehruoydeef/Yin-Yang#24]
The at this time latest release v1.0 does not run on my updated KDE Neon. Launching the AppImage from the cmdline gives:
'''
[39493] Error loading Python lib '/tmp/_MEIMrEuob/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIMrEuob/libpython3.6m.so.1.0)
'''

**Comment by daehruoydeef** [comment]
Do you have GLIBC installed? It looks like the build Script I am using pyInstaller is needing those.

You should install this using sudo apt-get install glibc.

**Comment by brenthuisman** [comment]
`glibc` is not a package on Ubuntu, but it should be available anyway, shouldn't it? `ldd --version` betrays that my version of Ubuntu (18.04) is built with glibc 2.27. Not sure why you need to link against that anyway, for me Python + Qt for Python does not require a specific version of glibc.

**Comment by daehruoydeef** [comment]
This is really weird and I cannot help you with that. I am shipping a bundled python version and the binary should include everything that is needed. Did you resolved it by now? If not I will leave this issue open, maybe other People are able to help you out.

**Comment by brenthuisman** [comment]
I have not resolved it. The only way is by overriding the glibc that the appimage uses (namely, 2.28).

I think you should see if you can build the AppImage without glibc, I think the excludelist should be used for that, e.g.:
https://github.com/AppImage/pkg2appimage/blob/master/excludelist

**Comment by bipox** [comment]
I have the same issue as brenthuisman in KDE Neon.

It works in Manjaro KDE.

**Comment by falko** [comment]
Same problem on Ubuntu 18.04.3 LTS. Running `sudo apt install libc6` shows that version 2.27 is installed:

```
libc6 is already the newest version (2.27-3ubuntu1).
```

**Comment by daehruoydeef** [comment]
We have switched to a new installation process see the readme for more information.
