### ISSUE TITLE
Doesn't change GNOME Shell theme

### ISSUE THREAD

**Issue by jordi-7** [daehruoydeef/Yin-Yang#28]
At the moment it only changes the application theme but not the shell theme in Gnome.

**Comment by jordi-7** [comment]
Current code that changes the applications theme:
gsettings set org.gnome.desktop.interface gtk-theme Plata-Noir-Compact

Code that changes the Shell theme should be added:
gsettings set org.gnome.shell.extensions.user-theme name "Plata-Noir-Compact"

**Comment by jordi-7** [comment]
Opened the following pull request with the appropiate changes: #29

**Comment by daehruoydeef** [comment]
Thanks Jordi, I just merged this. I will add your name to the contributors list.

**Comment by jordi-7** [comment]
Thanks! Looking forward to try it. Feel free to close this issue

**Comment by daehruoydeef** [comment]
Keep in mind that this need a rebuild of the appImage to work. Alternativly you can install this manually and it should work right away.
