### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by neverix** [daehruoydeef/Yin-Yang#4]
What is the license of this project?

**Comment by daehruoydeef** [comment]
I just updated the LICENSE to the MIT License. You can easily add programs if you create a file inside the [bin/plugins](https://github.com/daehruoydeef/Yin-Yang/tree/master/bin/plugins) folder. You can finally call your plugin after importing it and calling it like it is [shown here ](https://github.com/daehruoydeef/Yin-Yang/blob/master/bin/yin_yang.py#L38)

If you want to add programs or ideas I would be really happy if we could merge this into the official repository afterwards.
