### ISSUE TITLE
Fix .desktop file

### ISSUE THREAD

**Issue by l0drex** [daehruoydeef/Yin-Yang#41]
There are some issues in the .desktop file that is created on installation:
- the app is called with the `-gui` option, although this option does not exist
- the categories are weird, should be for example `Utility; System`
- the icon doesn't look that good, very pixelated and has a non-transparent background.

**Comment by daehruoydeef** [comment]
Thanks just fixed the points you mentioned, I will update the repo in the following days and plan on providing a new installation process. I plan on releasing the next version of yin-yang soon with the new suntime option.
