### ISSUE TITLE
install.sh: home directory not detected

### ISSUE THREAD

**Issue by andrei-pavel** [daehruoydeef/Yin-Yang#44]
```
install.sh: 42: cannot create /home//.local/share/applications/Yin-Yang.desktop: Directory nonexistent
```
Maybe it should use `${HOME}` instead of `/home/${SUDO_USER}` just like earlier in the script.
Thank you!

**Comment by daehruoydeef** [comment]
Can you try again to install this application, simply run the install.sh script with sh. You will get prompted to enter your password.

**Comment by cenkozan** [comment]
Hi. Thanks SO MUCH for this. I have the same problem but I'm not being asked any password - Ubuntu 20.
Kindly help. Hope you can read a comment on a closed thread :/
Thanks.

**Comment by daehruoydeef** [comment]
Yes, you could try to install the install.sh with sudo.
So use it like
`sudo sh install.sh`
i believe that ubuntu changed the behavior how this is handled.

**Comment by cenkozan** [comment]
Thanks so much, Oscar. That worked. Cheers.
