### ISSUE TITLE
Schedule doesn't work if time for dark theme is set after 00:00

### ISSUE THREAD

**Issue by l0drex** [daehruoydeef/Yin-Yang#45]
System: Manjaro with KDE Plasma, but should be on every system

 ### Expected behavior
Dark theme should be enabled after time for dark theme, even if the time is set to after 00:00 and before the time for light theme.

### What happend
Dark theme is enabled before 00:00 and after time for light theme.

**Comment by daehruoydeef** [comment]
Great catch, I never expected that someone would set the dark theme to be after 00:00. I will try to fix and set better time intervals.

[this is the line of interest that handles the current interval](https://github.com/daehruoydeef/Yin-Yang/blob/77600601e3e333ac76fcc4a8c46aaaf6e9836fef/src/yin_yang.py#L169)

**Comment by l0drex** [comment]
I realized this working on the browser extension. I think it could already help to just swap the returns if the dark theme gets activated before light theme.
