### ISSUE TITLE
Launch in background, don't show yin-yang dialog upon boot

### ISSUE THREAD

**Issue by tneo** [daehruoydeef/Yin-Yang#46]
I'm very happy that issue #27 is resolved. I added Yin-Yang to the startup/ shutdown section under system settings. I added the option -s for launching. This triggers the window for yin-yang to be shown as well. Can an option be added to launch in the background without the pop-up window?

**Comment by daehruoydeef** [comment]
Is the problem that the Dialog shows or does not show, the title in conjunction with the description is a bit misleading.

What you can try:
1) Add Yin-Yang as a program to the Autostart Dialog
2) Inside the Application tab edit the Command that is used to run yin-yang. It should feature a -s at the end.

See the screenshot:
![image](https://user-images.githubusercontent.com/36965591/80303134-9873b300-87ae-11ea-90f2-e50fe04a8a90.png)

Please report back if this fixes it for you. I think I need to write better documentation for such behavior.

**Comment by tneo** [comment]
The problem is that when I get into my Plasma session I get this pop-up: 
![image](https://user-images.githubusercontent.com/6168186/80323206-4438f500-87e7-11ea-8c4b-845060d7a068.png)

I don't need to see that every time I log-in. I only need that when changing settings.

**Comment by daehruoydeef** [comment]
Yes I understand have you tried the solution I mentioned above? It is working great for me.

You need to add Yin-Yang as a program and edit the command that is used to run Yin&Yang add a `-s` at the end.

The full command will look like this 
`env QT_AUTO_SCREEN_SCALE_FACTOR=1 sh /usr/bin/yin-yang -s`

That way Yin&Yang will run in the background without opening a Popup on boot.

**Comment by tneo** [comment]
It works indeed. There were 2 entries in the startup section. Tried logging out and back in and all is OK. :)
