### ISSUE TITLE
HiDPI breaks layout

### ISSUE THREAD

**Issue by frumble** [daehruoydeef/Yin-Yang#5]
![yingyang-hidpi-mess](https://user-images.githubusercontent.com/1595877/54576656-5e57af80-49f9-11e9-8ffb-21f1fdfe7f3f.png)
Try forcing a custom font DPI in system settings, relogin and see for yourself. Here are 163 DPI on a 4K screen.

**Comment by daehruoydeef** [comment]
Thanks for the try out. I am only on full-hd and a retina screen and everything works fine. I read somewhere that there are specific QT5 flags to enable HiDPI support. I will look into this in the coming week.

**Comment by daehruoydeef** [comment]
Could you please run this command prior to starting Yin-Yang:

`export QT_AUTO_SCREEN_SCALE_FACTOR=1`

this should fix the qt scaling problem and I will update the source code on the next Yin-Yang release. If you like how Yin-Yang looks after this you can add this to your PATH Variable and make it permanent simply add it with:

open ~/.bashrc or ~/.zshrc
add the line:
export PATH=$PATH:QT_AUTO_SCREEN_SCALE_FACTOR=1

I would be happy to know if this works for you. Thank you for catching this bug!

**Comment by frumble** [comment]
Works!

**Comment by frumble** [comment]
Works!
But the bashrc line is the wrong approach because it overrides my global HiDPI settings of Plasma which are applied to most Qt and GTK+ programs just fine.

**Comment by daehruoydeef** [comment]
This is rather a "fix for just now". I try to find a better approach and get it working more stable.

**Comment by daehruoydeef** [comment]
@frumble hey I got HiDPI working now and it should only effect Yin-Yang
The way I know did it was by editing the .desktop file so the script that gets called looks like this

`exec=env QT_AUTO_SCREEN_SCALE_FACTOR=1 sh /usr/bin/yin-yang -gui`

I will close this issue since it seems like this fixed the Issue, if you run into the same Problem I will reactivate this issue.
