### ISSUE TITLE
Add separate icon theme, plasma theme and so on

### ISSUE THREAD

**Issue by neverix** [daehruoydeef/Yin-Yang#7]
I think that `yin-yang` could be improved by not only changing the Look & Feel but also the window manager theme, the icon theme and the plasma theme separately.

**Comment by alxlg** [comment]
AFAIK there isn't a command to switch icons, Plasma theme, widget themes and color palettes independently, there is only `lookandfeeltool` that switch Look&Feel package and it's what Yin-Yang uses.

**Comment by daehruoydeef** [comment]
I have looked into this and while it is possible to change the Icon theme it is not possible to let KDE accept those changes via the API they expose. In theory it would be possible but we probably need to wait for future KDE releases. Or you could simply use the workaround mentioned above.

**Comment by neverix** [comment]
[Here's what I found](https://cgit.kde.org/plasma-desktop.git/tree/kcms/icons/changeicons.cpp) (systemsettings5 source code) - this is the way KDE developers did it.
So in theory, it _is_ possible to do, we just have to do some digging.
