### ISSUE TITLE
Make the code PEP 8 compliant

### ISSUE THREAD

**Issue by neverix** [daehruoydeef/Yin-Yang#9]
[PEP 8](https://www.python.org/dev/peps/pep-0008/) is the accepted coding style for Python. This project has to be reworked to make it PEP 8 compliant.

**Comment by daehruoydeef** [comment]
Thanks I will look into this. But unfortunaly my time is limited and this is not the highest priority right now. I could really need some help with this since I am not familiar with all the PEP8 coding conventions but would really like to get this project up to the latest code conventions.

**Comment by Rabidax** [comment]
I'll do it if that's ok with you, I've been looking for an easy issue to tackle for my first steps in open source contributing :)

**Comment by daehruoydeef** [comment]
@Rabidax you sure earned a place on the contributors list! Thank you so much for your effort.
If you want your Desktop to be supported please open another Issue and I am sure we can make this happen. Again thank you for your help.

**Comment by Rabidax** [comment]
You probably need to edit the wiki to reflect those changes. I saw Contributing.md uses CamelCase.

**Comment by neverix** [comment]
Oh, so cool! Thanks @Rabidax!

**Comment by daehruoydeef** [comment]
@Rabidax thanks I just fixed the Wiki, again thank you for your help. Stuff like this is really bringing the project forward!
